<?php

namespace AppBundle\Repository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByTheme($thm){
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM association p WHERE p.theme = :thm';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['thm' => $thm]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }

    public function getByName($name){
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM association p WHERE p.name = :name';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['name' => $name]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
