<?php

namespace AppBundle\Repository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserDonation($id){
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM donation c WHERE c.user_id = :id ORDER BY id DESC LIMIT 1';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['id' => $id]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
