<?php

namespace AppBundle\Repository;

/**
 * partnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class partnerRepository extends \Doctrine\ORM\EntityRepository
{
}
