<?php

namespace AppBundle\Repository;

/**
 * projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projetRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllByAsso($assoc){
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT projet_id FROM association_projet p WHERE p.association_id = :assoc ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['assoc' => $assoc]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }

    public function getAllProj($id,$thm){
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM projet p,partner pa WHERE p.id = :id AND p.points < p.max_point AND p.theme =:thm AND p.id = pa.id';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['id' => $id,'thm' => $thm]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
